import type { Metadata } from "next";
import { Alumni_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const fran = Alumni_Sans({
  subsets: ["latin"],
  weight: "500"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-stone-950 text-slate-100">
      <body className={fran.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
